###7.1 One-way analysis of variance
library(ISwR)
attach(red.cell.folate)
summary(red.cell.folate) #this dataset is marked with three factor values

anova(lm(folate~ventilation)) #between group->factor name(SSDb and MSb), within group->Residuals(SSDw and MSw)

attach(juul)
juul$tanner=factor(juul$tanner,labels=c("I","II","III","IV","V")) #important to change vector to factor
detach(juul)
attach(juul)
anova(lm(igf1~tanner))

#7.1.1 Pairwise comparisons and multiple testing
summary(lm(folate~ventilation))
pairwise.t.test(folate,ventilation,p.adj="bonferroni")
pairwise.t.test(folate,ventilation) #p-value adjustment due to Holm

#7.1.2 Relaxing the variance assumption
oneway.test(folate~ventilation)
pairwise.t.test(folate,ventilation,pool.sd=F)

#7.1.3 Graphical representation
xbar=tapply(folate,ventilation,mean)
s=tapply(folate,ventilation,sd)
n=tapply(folate,ventilation,length)
sem=s/sqrt(n)
stripchart(folate~ventilation,method="jitter",jitter=0.05,pch=16,vert=T)
arrows(1:3,xbar+sem,1:3,xbar-sem,angle=90,code=3,length=.1)
lines(1:3,xbar,pch=4,type="b",cex=2)

#7.1.4 Bartlett's test of idential variances
bartlett.test(folate~ventilation)

###7.2 Kruskal-Wallis test (non-parametric)
kruskal.test(folate~ventilation)

###7.3 Two-way analysis of variance
attach(heart.rate)
heart.rate #the dataset is generated by using data.frame() and gl().
gl(9,1,36)
gl(4,9,36,labels=c(0,30,60,120))

anova(lm(hr~subj+time))
#7.3.1 Graphic representation
interaction.plot(time,subj,hr)
interaction.plot(ordered(time),subj,hr)

###7.4 The Friedman test (non-parametric)
friedman.test(hr~time|subj,data=heart.rate) #time WITHIN subject
friedman.test(hr~subj|time,data=heart.rate) #subject WITHIN time

###7.5 The ANOVA table in regression analysis
attach(thuesen)
head(thuesen)
lm.velo=lm(blood.glucose~short.velocity)
anova(lm.velo)

### Exercises
#7.1
zelazo.lm=data.frame(value=c(zelazo$active,zelazo$passive,zelazo$none,zelazo$ctr.8w),group=gl(4,6,23,labels=c("active","passive","none","ctr.8w")))
attach(zelazo.lm)
anova(lm(value~group))
# using unlist()
unlist(zelazo)

#7.2
lung
attach(lung)
lm.lung=lm(volume~method+subject)
anova(lm.lung)
summary(lm.lung)

#7.3
kruskal.test(value~group)
friedman.test(volume~method|subject,data=lung)

#7.4
head(juul)
tapply(sqrt(igf1),tanner,sd,na.rm=T)
oneway.test(sqrt(igf1)~tanner)
